export const primaryGrey = '#f2f2f2'
export const primaryLightGrey = '#f8f8f8'
export const secondaryGrey = '#878787'
export const primaryCian = '#34bdb2'
export const primaryLightCian = '#DFF6F4'
